gemfile: Gemfile
verify_signatures: false

PreCommit:
  BundleCheck:
    enabled: true

  FixMe:
    enabled: true
    keywords: ["FIXME"]
    exclude:
      - .overcommit.yml

  LocalPathsInGemfile:
    enabled: true

  RailsSchemaUpToDate:
    enabled: true

  RuboCop:
    enabled: true
    on_warn: fail

  TrailingWhitespace:
    enabled: true
    exclude:
      - "**/db/schema.rb"

  YamlSyntax:
    enabled: true

PostCheckout:
  ALL:
    quiet: true
