version: '1'
services:
  db:
    image: postgres:latest
    container_name: sample-app-postgres-latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: sample_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  postgres_data: {}
